// Generated by gencpp from file grc_tutorial/SrvTutorial.msg
// DO NOT EDIT!


#ifndef GRC_TUTORIAL_MESSAGE_SRVTUTORIAL_H
#define GRC_TUTORIAL_MESSAGE_SRVTUTORIAL_H

#include <ros/service_traits.h>


#include <grc_tutorial/SrvTutorialRequest.h>
#include <grc_tutorial/SrvTutorialResponse.h>


namespace grc_tutorial
{

struct SrvTutorial
{

typedef SrvTutorialRequest Request;
typedef SrvTutorialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvTutorial
} // namespace grc_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grc_tutorial::SrvTutorial > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::grc_tutorial::SrvTutorial&) { return value(); }
};

template<>
struct DataType< ::grc_tutorial::SrvTutorial > {
  static const char* value()
  {
    return "grc_tutorial/SrvTutorial";
  }

  static const char* value(const ::grc_tutorial::SrvTutorial&) { return value(); }
};


// service_traits::MD5Sum< ::grc_tutorial::SrvTutorialRequest> should match 
// service_traits::MD5Sum< ::grc_tutorial::SrvTutorial > 
template<>
struct MD5Sum< ::grc_tutorial::SrvTutorialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grc_tutorial::SrvTutorial >::value();
  }
  static const char* value(const ::grc_tutorial::SrvTutorialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grc_tutorial::SrvTutorialRequest> should match 
// service_traits::DataType< ::grc_tutorial::SrvTutorial > 
template<>
struct DataType< ::grc_tutorial::SrvTutorialRequest>
{
  static const char* value()
  {
    return DataType< ::grc_tutorial::SrvTutorial >::value();
  }
  static const char* value(const ::grc_tutorial::SrvTutorialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grc_tutorial::SrvTutorialResponse> should match 
// service_traits::MD5Sum< ::grc_tutorial::SrvTutorial > 
template<>
struct MD5Sum< ::grc_tutorial::SrvTutorialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grc_tutorial::SrvTutorial >::value();
  }
  static const char* value(const ::grc_tutorial::SrvTutorialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grc_tutorial::SrvTutorialResponse> should match 
// service_traits::DataType< ::grc_tutorial::SrvTutorial > 
template<>
struct DataType< ::grc_tutorial::SrvTutorialResponse>
{
  static const char* value()
  {
    return DataType< ::grc_tutorial::SrvTutorial >::value();
  }
  static const char* value(const ::grc_tutorial::SrvTutorialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRC_TUTORIAL_MESSAGE_SRVTUTORIAL_H
