// Generated by gencpp from file grc_tutorial/WashTheDishesGoal.msg
// DO NOT EDIT!


#ifndef GRC_TUTORIAL_MESSAGE_WASHTHEDISHESGOAL_H
#define GRC_TUTORIAL_MESSAGE_WASHTHEDISHESGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grc_tutorial
{
template <class ContainerAllocator>
struct WashTheDishesGoal_
{
  typedef WashTheDishesGoal_<ContainerAllocator> Type;

  WashTheDishesGoal_()
    : number_of_minutes(0)  {
    }
  WashTheDishesGoal_(const ContainerAllocator& _alloc)
    : number_of_minutes(0)  {
  (void)_alloc;
    }



   typedef int32_t _number_of_minutes_type;
  _number_of_minutes_type number_of_minutes;





  typedef boost::shared_ptr< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> const> ConstPtr;

}; // struct WashTheDishesGoal_

typedef ::grc_tutorial::WashTheDishesGoal_<std::allocator<void> > WashTheDishesGoal;

typedef boost::shared_ptr< ::grc_tutorial::WashTheDishesGoal > WashTheDishesGoalPtr;
typedef boost::shared_ptr< ::grc_tutorial::WashTheDishesGoal const> WashTheDishesGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grc_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'grc_tutorial': ['/home/arvind/ROS-tutorial/grc_ws/src/grc_tutorial/msg', '/home/arvind/ROS-tutorial/grc_ws/devel/share/grc_tutorial/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08fc95c12e8d6b627afb5f6c3337b8ec";
  }

  static const char* value(const ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08fc95c12e8d6b62ULL;
  static const uint64_t static_value2 = 0x7afb5f6c3337b8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grc_tutorial/WashTheDishesGoal";
  }

  static const char* value(const ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal\n\
\n\
int32 number_of_minutes\n\
";
  }

  static const char* value(const ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number_of_minutes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WashTheDishesGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grc_tutorial::WashTheDishesGoal_<ContainerAllocator>& v)
  {
    s << indent << "number_of_minutes: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number_of_minutes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRC_TUTORIAL_MESSAGE_WASHTHEDISHESGOAL_H
