// Auto-generated. Do not edit!

// (in-package grc_tutorial.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class WashTheDishesFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.last_dishes_washed = null;
    }
    else {
      if (initObj.hasOwnProperty('last_dishes_washed')) {
        this.last_dishes_washed = initObj.last_dishes_washed
      }
      else {
        this.last_dishes_washed = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type WashTheDishesFeedback
    // Serialize message field [last_dishes_washed]
    bufferOffset = _serializer.string(obj.last_dishes_washed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type WashTheDishesFeedback
    let len;
    let data = new WashTheDishesFeedback(null);
    // Deserialize message field [last_dishes_washed]
    data.last_dishes_washed = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.last_dishes_washed.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'grc_tutorial/WashTheDishesFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '09bfa3b29e79134b6cff66a16bb45868';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    #Feedback
    string last_dishes_washed
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new WashTheDishesFeedback(null);
    if (msg.last_dishes_washed !== undefined) {
      resolved.last_dishes_washed = msg.last_dishes_washed;
    }
    else {
      resolved.last_dishes_washed = ''
    }

    return resolved;
    }
};

module.exports = WashTheDishesFeedback;
